### ISSUE TITLE
calculate sinuosity for north vs south

### ISSUE THREAD

**Issue by mnowatzki** [csdms-espin/migrators#7]

**Comment by noshin18** [comment]
def calculate_sinuosity(self):
    """method for calculating sinuosity of the channel centerline"""

    channel = self.channels[-1]  # Get the last channel object
    x = channel.x
    y = channel.y

    # Calculate the total path length along the channel centerline
    total_path_length = 0
    for i in range(len(x) - 1):
        total_path_length += ((x[i+1] - x[i]) ** 2 + (y[i+1] - y[i]) ** 2) ** 0.5

    # Calculate the straight-line distance between the start and end of the channel
    straight_distance = ((x[-1] - x[0]) ** 2 + (y[-1] - y[0]) ** 2) ** 0.5

    # Calculate sinuosity
    sinuosity = total_path_length / straight_distance

    return sinuosity

**Comment by josiearcuri** [comment]
looks good!
